[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "contracts/out"
script = "contracts/script"
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"
libs = ["dependencies"]
solc_version = "0.8.20"

[soldeer]
recursive_deps = true
remappings_location = "txt"
remappings_version = false

[dependencies]
tnt-core = "0.1.0"
forge-std = "1.9.5"
"@openzeppelin-contracts" = "5.1.0"
"@openzeppelin-contracts-upgradeable" = "4.8.1"
"@layerzerolabs-lz-evm-messagelib-v2" = "3.0.50"
"@layerzerolabs-lz-evm-protocol-v2" = "3.0.50"
"@layerzerolabs-lz-evm-v1-0-7" = "3.0.50"
solidity-bytes-utils = { version = "0.8.2", git = "https://github.com/GNSPS/solidity-bytes-utils.git", tag = "v0.8.2" }
